version: '3'
services:
  web:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    
