version: "3"

services:
  nginx:
    container_name: mynginx
    restart: always
    image: nginx7
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/ssl/certs:/etc/nginx/certs
      - /etc/ssl/private:/etc/nginx/certs/private
  app:
    container_name: newapp
    restart: always
    image: finalapp
    ports:
      - "3000:3000"
    volumes:
      - /home/lizzy/project1/app2:/app
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - /home/lizzy/project1/mongo:/data/db
 
